// ============================================
// 100 Energy Books for Overseas Chinese Business Leaders
// ============================================

const BOOKS = [
  // 1-20: Energy Fundamentals & Policy
  { id:1, title_cn:"能源与文明：一段历史", title_en:"Energy and Civilization: A History", author:"Vaclav Smil", cat_cn:"能源通史", cat_en:"Energy History" },
  { id:2, title_cn:"能源转型", title_en:"Energy Transitions", author:"Vaclav Smil", cat_cn:"能源转型", cat_en:"Energy Transition" },
  { id:3, title_cn:"能源革命", title_en:"The Energy Revolution", author:"Alex Lightman", cat_cn:"能源政策", cat_en:"Energy Policy" },
  { id:4, title_cn:"大转折：能源转型与经济未来", title_en:"The Big Switch", author:"James M. Jasper", cat_cn:"能源转型", cat_en:"Energy Transition" },
  { id:5, title_cn:"能源与国家权力", title_en:"Energy and National Power", author:"Mark H. Hayes", cat_cn:"能源地缘政治", cat_en:"Energy Geopolitics" },
  { id:6, title_cn:"石油帝国", title_en:"The Prize", author:"Daniel Yergin", cat_cn:"石油历史", cat_en:"Oil History" },
  { id:7, title_cn:"争夺能源", title_en:"The Quest", author:"Daniel Yergin", cat_cn:"能源地缘政治", cat_en:"Energy Geopolitics" },
  { id:8, title_cn:"能源地缘政治新地图", title_en:"The New Map", author:"Daniel Yergin", cat_cn:"能源地缘政治", cat_en:"Energy Geopolitics" },
  { id:9, title_cn:"能源与人类未来", title_en:"Our Renewable Future", author:"Richard Heinberg", cat_cn:"可再生能源", cat_en:"Renewable Energy" },
  { id:10, title_cn:"碳交易", title_en:"Carbon Trading", author:"Larry Lohmann", cat_cn:"碳市场", cat_en:"Carbon Market" },
  { id:11, title_cn:"气候变化经济学", title_en:"The Economics of Climate Change", author:"Nicholas Stern", cat_cn:"气候经济", cat_en:"Climate Economics" },
  { id:12, title_cn:"热浪：全球化与气候变化的未来", title_en:"Heat", author:"George Monbiot", cat_cn:"气候变化", cat_en:"Climate Change" },
  { id:13, title_cn:"不可能的革命： minibind 研究与可再生能源", title_en:"The Renewable Revolution", author:"Suzanne C. Hunt", cat_cn:"可再生能源", cat_en:"Renewable Energy" },
  { id:14, title_cn:"能源投资与资本市场", title_en:"Energy Investment and Capital Markets", author:"Tom James", cat_cn:"能源投资", cat_en:"Energy Investment" },
  { id:15, title_cn:"中国能源政策与发展", title_en:"China's Energy Policy", author:"Zhao Jianping", cat_cn:"中国能源", cat_en:"China Energy" },
  { id:16, title_cn:"能源法与监管", title_en:"Energy Law and Regulation", author:"Peter Cameron", cat_cn:"能源法律", cat_en:"Energy Law" },
  { id:17, title_cn:"能源贫困与公正转型", title_en:"Energy Poverty and Just Transition", author:"Benjamin K. Sovacool", cat_cn:"能源公平", cat_en:"Energy Justice" },
  { id:18, title_cn:"石油时代的终结", title_en:"The End of Oil", author:"Paul Roberts", cat_cn:"石油", cat_en:"Oil" },
  { id:19, title_cn:"绿色致富", title_en:"Green to Gold", author:"Daniel C. Esty", cat_cn:"绿色商业", cat_en:"Green Business" },
  { id:20, title_cn:"能源风险管理", title_en:"Energy Risk Management", author:"Tom James", cat_cn:"能源风险", cat_en:"Energy Risk" },
  // 21-40: Renewable Energy & Clean Tech
  { id:21, title_cn:"太阳能不能", title_en:"Solar Revolution", author:"Travis Bradford", cat_cn:"太阳能", cat_en:"Solar Energy" },
  { id:22, title_cn:"光伏产业", title_en:"The Solar Economy", author:"Hermann Scheer", cat_cn:"太阳能", cat_en:"Solar Energy" },
  { id:23, title_cn:"风力发电原理", title_en:"Wind Energy Explained", author:"James F. Manwell", cat_cn:"风能", cat_en:"Wind Energy" },
  { id:24, title_cn:"储能技术", title_en:"Energy Storage", author:"Ruud Kempener", cat_cn:"储能", cat_en:"Energy Storage" },
  { id:25, title_cn:"电池材料", title_en:"Battery Materials", author:"Arunachala Nadar M Kannan", cat_cn:"电池", cat_en:"Battery" },
  { id:26, title_cn:"锂电池世界", title_en:"Lithium-Ion Batteries", author:"Masaki Yoshio", cat_cn:"电池", cat_en:"Battery" },
  { id:27, title_cn:"氢能经济", title_en:"The Hydrogen Economy", author:"Jeremy Rifkin", cat_cn:"氢能", cat_en:"Hydrogen" },
  { id:28, title_cn:"氢能未来", title_en:"Hydrogen Futures", author:"David S. Scott", cat_cn:"氢能", cat_en:"Hydrogen" },
  { id:29, title_cn:"燃料电池原理", title_en:"Fuel Cell Fundamentals", author:"Ryan O'Hayre", cat_cn:"燃料电池", cat_en:"Fuel Cell" },
  { id:30, title_cn:"智能电网", title_en:"Smart Grid", author:"Clark W. Gellings", cat_cn:"智能电网", cat_en:"Smart Grid" },
  { id:31, title_cn:"电网2030", title_en:"Grid 2030", author:"Richard Metayer", cat_cn:"智能电网", cat_en:"Smart Grid" },
  { id:32, title_cn:"可再生能源手册", title_en:"Renewable Energy Handbook", author:"John Twidell", cat_cn:"可再生能源", cat_en:"Renewable Energy" },
  { id:33, title_cn:"清洁能源投资", title_en:"Clean Energy Investing", author:"Jeffrey R. Siegel", cat_cn:"能源投资", cat_en:"Energy Investment" },
  { id:34, title_cn:"能源效率", title_en:"Energy Efficiency", author:"Charles A. Lienau", cat_cn:"能效", cat_en:"Energy Efficiency" },
  { id:35, title_cn:"碳捕集与封存", title_en:"Carbon Capture and Storage", author:"B. P. McGrail", cat_cn:"CCUS", cat_en:"CCUS" },
  { id:36, title_cn:"生物质能源", title_en:"Bioenergy", author:"Anju Dahiya", cat_cn:"生物质", cat_en:"Bioenergy" },
  { id:37, title_cn:"地热能", title_en:"Geothermal Energy", author:"Ronald DiPippo", cat_cn:"地热", cat_en:"Geothermal" },
  { id:38, title_cn:"海洋能源", title_en:"Ocean Energy", author:"A. F. de O. Falcao", cat_cn:"海洋能", cat_en:"Ocean Energy" },
  { id:39, title_cn:"电力系统分析", title_en:"Power System Analysis", author:"John J. Grainger", cat_cn:"电力系统", cat_en:"Power Systems" },
  { id:40, title_cn:"电力市场设计", title_en:"Power Market Design", author:"Chris Harris", cat_cn:"电力市场", cat_en:"Power Market" },
  // 41-60: Oil, Gas & Nuclear
  { id:41, title_cn:"石油定价与市场", title_en:"Oil Pricing and Markets", author:"Daniel Yergin", cat_cn:"石油市场", cat_en:"Oil Market" },
  { id:42, title_cn:"页岩革命", title_en:"The Frackers", author:"Gregory Zuckerman", cat_cn:"页岩油气", cat_en:"Shale Oil & Gas" },
  { id:43, title_cn:"石油时代", title_en:"The Age of Oil", author:"Leonardo Maugeri", cat_cn:"石油", cat_en:"Oil" },
  { id:44, title_cn:"天然气革命", title_en:"The Natural Gas Revolution", author:"Michele R. Kirsch", cat_cn:"天然气", cat_en:"Natural Gas" },
  { id:45, title_cn:"LNG产业", title_en:"LNG: A Guide to the Industry", author:"Geoffrey E. Hadrill", cat_cn:"液化天然气", cat_en:"LNG" },
  { id:46, title_cn:"核能争议", title_en:"Nuclear Energy in the 21st Century", author:"Ian Hore-Lacy", cat_cn:"核能", cat_en:"Nuclear" },
  { id:47, title_cn:"核聚变能源", title_en:"Fusion: The Energy of the Universe", author:"Garry McCracken", cat_cn:"核聚变", cat_en:"Nuclear Fusion" },
  { id:48, title_cn:"核电安全", title_en:"Nuclear Safety", author:"J. Brian Knowles", cat_cn:"核安全", cat_en:"Nuclear Safety" },
  { id:49, title_cn:"能源项目管理", title_en:"Energy Project Management", author:"David G. Carmichael", cat_cn:"项目管理", cat_en:"Project Management" },
  { id:50, title_cn:"能源工程经济学", title_en:"Engineering Economics for Energy", author:"Robert Park", cat_cn:"能源经济", cat_en:"Energy Economics" },
  { id:51, title_cn:"石油化学工程", title_en:"Petroleum Chemical Engineering", author:"James H. Gary", cat_cn:"石化", cat_en:"Petrochemical" },
  { id:52, title_cn:"钻井工程", title_en:"Drilling Engineering", author:"J.J. Azar", cat_cn:"钻井", cat_en:"Drilling" },
  { id:53, title_cn:"储层工程", title_en:"Reservoir Engineering", author:"L. P. Dake", cat_cn:"储层", cat_en:"Reservoir" },
  { id:54, title_cn:"油气管道", title_en:"Oil and Gas Pipelines", author:"Boyko Matev", cat_cn:"管道", cat_en:"Pipeline" },
  { id:55, title_cn:"炼油工艺", title_en:"Refining Processes", author:"Pierre Leprince", cat_cn:"炼油", cat_en:"Refining" },
  { id:56, title_cn:"能源交易与风险管理", title_en:"Energy Trading and Risk Management", author:"Iris Marie Mack", cat_cn:"能源交易", cat_en:"Energy Trading" },
  { id:57, title_cn:"石油市场建模", title_en:"Modeling Oil Markets", author:"H. G. Huntington", cat_cn:"石油市场", cat_en:"Oil Market" },
  { id:58, title_cn:"能源衍生品", title_en:"Energy Derivatives", author:"Tom James", cat_cn:"能源金融", cat_en:"Energy Finance" },
  { id:59, title_cn:"小型模块化反应堆", title_en:"Small Modular Reactors", author:"Daniel T. Ingersoll", cat_cn:"核能", cat_en:"Nuclear" },
  { id:60, title_cn:"核燃料循环", title_en:"Nuclear Fuel Cycle", author:"Michael D. Carell", cat_cn:"核能", cat_en:"Nuclear" },
  // 61-80: Space Energy & Future Tech
  { id:61, title_cn:"太空太阳能", title_en:"Space Solar Power", author:"Peter E. Glaser", cat_cn:"太空能源", cat_en:"Space Energy" },
  { id:62, title_cn:"太空经济", title_en:"The Space Economy", author:"James Vedda", cat_cn:"太空经济", cat_en:"Space Economy" },
  { id:63, title_cn:"太空资源", title_en:"Space Resources", author:"William A. Birdsell", cat_cn:"太空资源", cat_en:"Space Resources" },
  { id:64, title_cn:"月球经济", title_en:"Lunar Economics", author:"Madhu Thangavelu", cat_cn:"月球经济", cat_en:"Lunar Economy" },
  { id:65, title_cn:"小行星采矿", title_en:"Asteroid Mining", author:"John S. Lewis", cat_cn:"太空采矿", cat_en:"Space Mining" },
  { id:66, title_cn:"能源物理学", title_en:"Energy Physics", author:"A. W. Culp", cat_cn:"能源物理", cat_en:"Energy Physics" },
  { id:67, title_cn:"能源材料", title_en:"Energy Materials", author:"Gerhard F. Swiegers", cat_cn:"能源材料", cat_en:"Energy Materials" },
  { id:68, title_cn:"纳米能源", title_en:"Nano Energy", author:"Zhong Lin Wang", cat_cn:"纳米技术", cat_en:"Nanotechnology" },
  { id:69, title_cn:"能源互联网", title_en:"Energy Internet", author:"Jeremy Rifkin", cat_cn:"能源互联网", cat_en:"Energy Internet" },
  { id:70, title_cn:"人工智能与能源", title_en:"AI and Energy", author:"James L. Sweeney", cat_cn:"AI与能源", cat_en:"AI & Energy" },
  { id:71, title_cn:"区块链能源交易", title_en:"Blockchain Energy Trading", author:"Stephen J. Park", cat_cn:"区块链", cat_en:"Blockchain" },
  { id:72, title_cn:"电动车革命", title_en:"The Electric Vehicle Revolution", author:"James Carter", cat_cn:"电动汽车", cat_en:"EV" },
  { id:73, title_cn:"微电网设计", title_en:"Microgrid Design", author:"Stephen M. Asare", cat_cn:"微电网", cat_en:"Microgrid" },
  { id:74, title_cn:"能源大数据", title_en:"Big Data in Energy", author:"Omer Tan", cat_cn:"大数据", cat_en:"Big Data" },
  { id:75, title_cn:"气候工程", title_en:"Climate Engineering", author:"David Keith", cat_cn:"地球工程", cat_en:"Geoengineering" },
  { id:76, title_cn:"能源与社会", title_en:"Energy and Society", author:"Harold H. Schobert", cat_cn:"能源社会", cat_en:"Energy & Society" },
  { id:77, title_cn:"碳中和路径", title_en:"Pathways to Carbon Neutrality", author:"Massamba Théo Diop", cat_cn:"碳中和", cat_en:"Carbon Neutrality" },
  { id:78, title_cn:"绿色金融", title_en:"Green Finance", author:"Giorgia Oggioni", cat_cn:"绿色金融", cat_en:"Green Finance" },
  { id:79, title_cn:"能源创新系统", title_en:"Energy Innovation Systems", author:"Staffan Jacobsson", cat_cn:"能源创新", cat_en:"Energy Innovation" },
  { id:80, title_cn:"可再生能源并网", title_en:"Renewable Energy Integration", author:"Lawrence E. Jones", cat_cn:"并网", cat_en:"Grid Integration" },
  // 81-100: Business & Investment in Energy
  { id:81, title_cn:"能源公司估值", title_en:"Energy Company Valuation", author:"Francisco B. Sosa", cat_cn:"能源估值", cat_en:"Energy Valuation" },
  { id:82, title_cn:"能源并购", title_en:"Energy M&A", author:"Michael T. O'Donnell", cat_cn:"能源并购", cat_en:"Energy M&A" },
  { id:83, title_cn:"石油公司战略", title_en:"Oil Company Strategy", author:"Paul H. Frankel", cat_cn:"石油战略", cat_en:"Oil Strategy" },
  { id:84, title_cn:"能源创业", title_en:"Energy Entrepreneurship", author:"Kelly L. Schultz", cat_cn:"能源创业", cat_en:"Energy Entrepreneurship" },
  { id:85, title_cn:"清洁技术投资", title_en:"Cleantech Investing", author:"William L. Liguori", cat_cn:"清洁技术", cat_en:"Cleantech" },
  { id:86, title_cn:"能源私募股权", title_en:"Energy Private Equity", author:"James E. Schrager", cat_cn:"私募股权", cat_en:"Private Equity" },
  { id:87, title_cn:"能源基础设施投资", title_en:"Energy Infrastructure Investment", author:"Peter R. Fusaro", cat_cn:"基础设施", cat_en:"Infrastructure" },
  { id:88, title_cn:"电力公司管理", title_en:"Power Utility Management", author:"John D. Lamont", cat_cn:"电力管理", cat_en:"Utility Management" },
  { id:89, title_cn:"能源供应链", title_en:"Energy Supply Chain", author:"V. K. Sethi", cat_cn:"供应链", cat_en:"Supply Chain" },
  { id:90, title_cn:"能源会计与审计", title_en:"Energy Accounting and Auditing", author:"C. Wei", cat_cn:"能源会计", cat_en:"Energy Accounting" },
  { id:91, title_cn:"能源合同与法律", title_en:"Energy Contracts and Law", author:"Peter Cameron", cat_cn:"能源法律", cat_en:"Energy Law" },
  { id:92, title_cn:"国际能源贸易", title_en:"International Energy Trade", author:"E. M. Khartukov", cat_cn:"能源贸易", cat_en:"Energy Trade" },
  { id:93, title_cn:"能源企业数字化转型", title_en:"Energy Digital Transformation", author:"Christoph L. Stroh", cat_cn:"数字化", cat_en:"Digitalization" },
  { id:94, title_cn:"能源品牌管理", title_en:"Energy Brand Management", author:"R. W. Hildreth", cat_cn:"品牌管理", cat_en:"Brand Management" },
  { id:95, title_cn:"能源企业ESG", title_en:"Energy ESG", author:"A. J. Krom", cat_cn:"ESG", cat_en:"ESG" },
  { id:96, title_cn:"可再生能源项目融资", title_en:"Renewable Energy Project Finance", author:"S. L. Chazan", cat_cn:"项目融资", cat_en:"Project Finance" },
  { id:97, title_cn:"能源市场分析", title_en:"Energy Market Analysis", author:"R. B. Lester", cat_cn:"市场分析", cat_en:"Market Analysis" },
  { id:98, title_cn:"能源预测与建模", title_en:"Energy Forecasting and Modeling", author:"G. S. Rothman", cat_cn:"能源预测", cat_en:"Energy Forecasting" },
  { id:99, title_cn:"能源政策与战略", title_en:"Energy Policy and Strategy", author:"Bent Sorensen", cat_cn:"能源政策", cat_en:"Energy Policy" },
  { id:100, title_cn:"文明的能源基础", title_en:"Energy at the Crossroads", author:"Vaclav Smil", cat_cn:"能源通论", cat_en:"General Energy" }
];
